# XDailyVouchers Configuration

# Daily reward base amount
dailyreward: 100

# Streak reward multiplier (0.1 = 10% increase per week)
strikreward: 0.1

# Messages
messages:
  reload: "&aPlugin configuration reloaded."
  reward: "&aYou received your daily reward: &6%amount% coins&a!"
  available: "&aYou have a daily reward available! Use &6/xdv daily&a to claim it!"
  help:
    - "&eXDailyVouchers Help"
    - "&7/xdv reload - Reload the plugin"
    - "&7/xdv voucher [name] - Create a voucher"
    - "&7/xdv give [vouchername] [user] [amount] - Give a voucher"
    - "&7/xdv daily - Show daily rewards GUI"
    - "&7/xdv dailyitem <day/week> <number> - Set daily/weekly item rewards"
    - "&7/xdv active <vouchername> <maxusers> <maxvouchers> - Activate voucher for redemption"
    - "&7/xdv deactive <vouchername> - Deactivate voucher redemption"
    - "&7/xdv redeem <vouchername> - Redeem an active voucher"